"""removed_fk

Revision ID: cbfef8e9f9b4
Revises: 99a977286386
Create Date: 2020-08-15 12:59:18.747378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfef8e9f9b4'
down_revision = '99a977286386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_permission_assigned_by_fkey', 'account_permission', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('account_permission_assigned_by_fkey', 'account_permission', 'account', ['assigned_by'], ['username'])
    # ### end Alembic commands ###
