"""filter update

Revision ID: e2c0d9b6bd7e
Revises: 7bc74b84754f
Create Date: 2020-08-24 13:15:40.146578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c0d9b6bd7e'
down_revision = '7bc74b84754f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter', sa.Column('permission_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'permission_required')
    # ### end Alembic commands ###
